MyFastFoodProject/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyFastFoodProject.DAL;
using MyFastFoodProject.Models;

namespace MyFastFoodProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        
            private readonly AppDbContext _context;
            public CategoryController(AppDbContext context)
            {
                _context = context;
            }
            public IActionResult Index()
            {
                return View(_context.Categories.ToList());
            }
            [HttpGet]
            public IActionResult Add()
            {
                ViewBag.Categories = _context.Categories.ToList();
                return View();
            }
            [HttpPost]
            public IActionResult Add(Category category)
            {
                _context.Categories.Add(category);
                _context.SaveChanges();
                return RedirectToAction("Index")
            }
            public IActionResult Delete(int id)
            {
                var c = _context.Categories.Find(id);
                if (c != null)
                {
                    _context.Categories.Remove(c);
                }
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            [HttpGet]
            public IActionResult Edit(int id)
            {
                ViewBag.Categories = _context.Categories.ToList();
                return View(_context.Categories.Find(id));
            }
            [HttpPost]
            public IActionResult Edit(Category newC)
            {
                var c = _context.Categories.Find(newC.Id);
                if (c != null)
                {
                    c.Name = newC.Name;
                    
                }
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            public IActionResult Activation(int id)
            {
                var category = _context.Categories.Find(id);
                if (category != null)
                {
                    if (category.IsActive)
                    {
                        category.IsActive = false;
                    }
                    else
                    {
                        category.IsActive = true;
                    }
                    _context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
   
}

MyFastFoodProject/Areas/Admin/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyFastFoodProject.DAL;
using MyFastFoodProject.Models;

namespace MyFastFoodProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DashBoardController : Controller
    {

        private readonly AppDbContext _appDbContext;
        private readonly SignInManager<ProgramUser> _signinmanager;
        public DashBoardController(AppDbContext appDbContext, SignInManager<ProgramUser> signInManager)
        {
            _appDbContext = appDbContext;
            _signinmanager = signInManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Logout()
        {

            await _signinmanager.SignOutAsync();
            return RedirectToAction("Index", "Home",new {area =""});
        }
    }
}

MyFastFoodProject/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Microsoft.EntityFrameworkCore;
using MyFastFoodProject.DAL;
using MyFastFoodProject.Extensions;
using MyFastFoodProject.Models;

namespace MyFastFoodProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly AppDbContext appDbContext;
        private readonly IWebHostEnvironment _env;
        public ProductsController(AppDbContext _appDbContext, IWebHostEnvironment env)
        {
            appDbContext = _appDbContext;
            _env = env; 

        }
        public IActionResult Index()
        {
            List<Products> products = appDbContext.Products.Include(x=>x.Category).ToList();
            return View(products);
        }
        public IActionResult Create()
        {
            ViewBag.Category= appDbContext.Categories.ToList();

            return View();
        }

        [HttpPost]
        public async Task < IActionResult> Create(Products model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Category = appDbContext.Categories.ToList();
                return View(model);
            }
            //TEK SEKILIN BAZAYA HEMDE PAPKAYA YUKLENMESI
            if (!model.ImgUrlBaseFile.IsImage())
            {
                ModelState.AddModelError("Photo", "Image type is not valid");
                return View(model);
            }
            string filename = await model.ImgUrlBaseFile.SaveFileAsync(_env.WebRootPath, "uploadProducts");

            model.ImgUrlBase = filename;

            appDbContext.Products.Add(model);
            appDbContext.SaveChanges();

            if (model.ImagesFiles != null)
            {
                foreach (var item in model.ImagesFiles)
                {
                    if (!item.IsImage())
                    {
                        ModelState.AddModelError("Photo", "Image type is not valid");
                        return View(model);
                    }
                    string filename2 = await item.SaveFileAsync(_env.WebRootPath, "uploadProducts");

                    Images images = new Images
                    {
                        ProductId = model.Id,
                        ImgUrl = filename2
                    };
                    appDbContext.Images.Add(images);
                    appDbContext.SaveChanges();

                }

            }

            return RedirectToAction("Index");
        }
   


        public IActionResult Edit(int id )
        {
            if (id == 0)
            {
                return NotFound();
            }
            ViewBag.Category = appDbContext.Categories.ToList();
            var model=  appDbContext.Products.Include(x=>x.Images).FirstOrDefault(x => x.Id == id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpPost]
        public async Task< IActionResult> Edit(Products productModel)
        {
            ViewBag.Category = appDbContext.Categories.ToList();
            var modelDb = appDbContext.Products.FirstOrDefault(x => x.Id == productModel.Id);
            modelDb.Title = productModel.Title;
            modelDb.Price = productModel.Price;
            modelDb.CategoryId = productModel.CategoryId;
            modelDb.Description = productModel.Description;
            modelDb.IsActive = productModel.IsActive;
            appDbContext.SaveChanges();

            if (modelDb == null)
            {
                return RedirectToAction("Index");
            }

            if (productModel.ImgUrlBaseFile != null)
            {
                if (!productModel.ImgUrlBaseFile.IsImage())
                {
                    ModelState.AddModelError("Photo", "Image type is not valid");
                    return View(productModel);
                }
                string filename = await productModel.ImgUrlBaseFile.SaveFileAsync(_env.WebRootPath, "uploadProducts");

                modelDb.ImgUrlBase = filename;
                appDbContext.SaveChanges();
            }


            if (productModel.ImagesFiles != null)
            {
                foreach (var item in productModel.ImagesFiles)
                {
                    if (!item.IsImage())
                    {
                        ModelState.AddModelError("Photo", "Image type is not valid");
                        return View(productModel);
                    }
                    string filename2 = await item.SaveFileAsync(_env.WebRootPath, "uploadProducts");

                    Images images = new Images
                    {
                        ProductId = productModel.Id,
                        ImgUrl = filename2
                    };
                    appDbContext.Images.Add(images);
                    appDbContext.SaveChanges();

                }
            }

            return RedirectToAction("Index");
        }
        public JsonResult DeleteImage(int id)
        {
            if (id != 0)
            {
                var model = appDbContext.Images.Find(id);
                appDbContext.Images.Remove(model);
                appDbContext.SaveChanges();
            }
            return Json(new
            {
                status = 200
            });

        }

        public JsonResult Delete(int id)
        {
            if (id == 0)
            {
                return Json(new
                {
                    status = 400
                });
            }
            var product = appDbContext.Products.Find(id);
            if (product != null)
            {
               product.IsActive = false;
                appDbContext.SaveChanges();
            }
            return Json(new
            {
                status = 200
            });

        }

    }
    }

MyFastFoodProject/Areas/Admin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyFastFoodProject.Controllers;
using MyFastFoodProject.DAL;
using MyFastFoodProject.Extensions;
using MyFastFoodProject.Models;

namespace MyFastFoodProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SliderController : Controller
    {
        private AppDbContext appDbContext;
        private readonly IWebHostEnvironment _env;
        public SliderController(AppDbContext _appDbContext, IWebHostEnvironment env)
        {

            appDbContext = _appDbContext;
            _env = env;
        }
        public IActionResult Index()
        {
            return View(appDbContext.Sliders.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Slider slider)
        {

            if (!FormFileExtensions.IsImage(slider.ImgFile))
            {
                ModelState.AddModelError("Photo", "Image type is not valid");
                return View(slider);
            }
            if (FormFileExtensions.IsImage(slider.ImgFile))
            {
                string filename = await slider.ImgFile.SaveFileAsync(_env.WebRootPath, "uploadSlider");
                slider.ImgUrl = filename;

                appDbContext.Sliders.Add(slider);
                appDbContext.SaveChanges();
            }
            else
            {
                return RedirectToAction("Create");
            }

            return RedirectToAction("Index");
        }
        public JsonResult Delete(int id)
        {
            if (id == 0)
            {
                return Json(new
                {
                    status = 400
                });
            }
            var slider = appDbContext.Sliders.Find(id);
            if (slider != null)
            {
                appDbContext.Sliders.Remove(slider);
                appDbContext.SaveChanges();
            }
            return Json(new
            {
                status = 200
            });

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var model = appDbContext.Sliders.FirstOrDefault(x => x.Id == id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(Slider slider)
        {
            var oldSlider = appDbContext.Sliders.Find(slider.Id);
            //if (!ModelState.IsValid)
            //{
            //    return View(slider);
            //}
            if (slider.ImgFile != null)
            {

                if (!slider.ImgFile.IsImage())
                {
                    ModelState.AddModelError("Photo", "Image type is not valid");
                    return View(slider);
                }
                string filename = await slider.ImgFile.SaveFileAsync(_env.WebRootPath, "uploadSlider");

                oldSlider.ImgUrl = filename;
            }
            oldSlider.Tittle = slider.Tittle;
            oldSlider.Subtitle = slider.Subtitle;
            oldSlider.Description = slider.Description;
            oldSlider.LastPrice = slider.LastPrice;
            oldSlider.NewPrice = slider.NewPrice;
            oldSlider.IsCheck = slider.IsCheck;
           
            appDbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MyFastFoodProject/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ProgramUser> SignInManager
@inject UserManager<ProgramUser> UserManager
<!doctype html>
<html lang="en">


<!-- Mirrored from themesbrand.com/skote/layouts/job-grid.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Apr 2024 08:13:16 GMT -->
<head>

    <meta charset="utf-8" />
    <title>Jobs Grid | Skote - Admin & Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="~/Adminassets/images/favicon.ico">

    <link href="~/Adminassets/libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css">

    <!-- Bootstrap Css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    @*     <link href="~/Adminassets/css/bootstrap.min.css" id="bootstrap-style" rel="stylesheet" type="text/css" />
    *@    <!-- Icons Css -->
    <link href="~/Adminassets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="~/Adminassets/css/app.min.css" id="app-style" rel="stylesheet" type="text/css" />
    <!-- App js -->
    <script src="~/Adminassets/js/plugin.js"></script>

    <style>
        .table .orta {
            padding-left: 80px;
        }
    </style>
    @RenderSection("Styles", false);
</head>

<body data-sidebar="dark">

    <!-- <body data-layout="horizontal" data-topbar="dark"> -->
    <!-- Begin page -->
    <div id="layout-wrapper">


        <header id="page-topbar">
            <div class="navbar-header">
                <div class="d-flex">
                    <!-- LOGO -->
                    <div class="navbar-brand-box">
                        <a href="index.html" class="logo logo-dark">
                            <span class="logo-sm">
                                <img src="~/Adminassets/images/logo.svg" alt="" height="22">
                            </span>
                            <span class="logo-lg">
                                <img src="~/Adminassets/images/logo-dark.png" alt="" height="17">
                            </span>
                        </a>

                        <a href="index.html" class="logo logo-light">
                            <span class="logo-sm">
                                <img src="~/Adminassets/images/logo-light.svg" alt="" height="22">
                            </span>
                            <span class="logo-lg">
                                <img src="~/Adminassets/images/logo-light.png" alt="" height="19">
                            </span>
                        </a>
                    </div>

                    <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect" id="vertical-menu-btn">
                        <i class="fa fa-fw fa-bars"></i>
                    </button>

                    <!-- App Search-->



                </div>

                <div class="d-flex">




                    <div class="dropdown d-inline-block">
                        <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="rounded-circle header-profile-user" src="~/Adminassets/images/users/avatar-1.jpg"
                                 alt="Header Avatar">
                                 @{
                                Task<ProgramUser> GetCurrentUserAsync() => UserManager.GetUserAsync(User);

                                var user = await GetCurrentUserAsync();
                                 }
                            <span class="d-none d-xl-inline-block ms-1" key="t-henry">Hello @user.Name Admin</span>
                            <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-end">
                            
                            
                           
                            <a asp-controller="DashBoard" asp-action="Logout" class="dropdown-item text-danger" ><i class="bx bx-power-off font-size-16 align-middle me-1 text-danger"></i> <span key="t-logout">Logout</span></a>
                        
                    </div>



                </div>
            </div>
        </header>

        <!-- ========== Left Sidebar Start ========== -->
        <div class="vertical-menu">

            <div data-simplebar class="h-100">

                <!--- Sidemenu -->
                <div id="sidebar-menu">
                    <!-- Left Menu Start -->
                    <ul class="metismenu list-unstyled" id="side-menu">
                        <li class="menu-title" key="t-menu">Menu</li>

                        <li>
                            <a asp-controller="DashBoard"asp-action="Index" asp-area="Admin">
                                
                                <i class="fas fa-home"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Category" asp-action="Index" asp-area="Admin" class="waves-effect">
                                <i class="bx bx-home-layout"></i>
                                <span key="t-layouts">Categories</span>
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Slider" asp-action="Index" asp-area="Admin" class="waves-effect">
                                <i class="bx bx-home-layout"></i>
                                <span key="t-layouts">Sliders</span>
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Products" asp-action="Index" asp-area="Admin" class="waves-effect">
                                <i class="bx bx-calendar"></i>
                                <span key="t-dashboards">Product</span>
                            </a>
                        </li>

                    </ul>
                </div>
                <!-- Sidebar -->
            </div>
        </div>
        <!-- Left Sidebar End -->
        <div class="main-content">
            @RenderBody()

        </div>
        <!-- end main content-->
    </div>
    <!-- /Right-bar -->
    <!-- Right bar overlay-->
    <div class="rightbar-overlay"></div>

    <!-- JAVASCRIPT -->
    <script src="~/Adminassets/libs/jquery/jquery.min.js"></script>
    <script src="~/Adminassets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Adminassets/libs/metismenu/metisMenu.min.js"></script>
    <script src="~/Adminassets/libs/simplebar/simplebar.min.js"></script>
    <script src="~/Adminassets/libs/node-waves/waves.min.js"></script>

    <script src="~/Adminassets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>

    <script src="~/Adminassets/js/pages/job-grid-list.init.js"></script>

    <script src="~/Adminassets/js/app.js"></script>
    @RenderSection("Scripts", false);


</body>

<!-- Mirrored from themesbrand.com/skote/layouts/job-grid.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Apr 2024 08:13:17 GMT -->
</html>